### ISSUE TITLE
adjust run time dependencies

### ISSUE THREAD

**Issue by tacaswell** [conda-forge/humanize-feedstock#48]
`importlib-metadata` is currently an unconditional dependency, but it is only required for python < 3.8.

Does CF still support older versions of Python and if not can we just bump the minimum supported version of the whole package to be above py38?

**Comment by hugovk** [comment]
I don't know about CF, but Python 3.7 is nearly EOL (in June: https://devguide.python.org/versions/), so we'll be dropping it upstream in https://github.com/python-humanize/humanize/ around that time.

**Comment by ocefpaf** [comment]
> `importlib-metadata` is currently an unconditional dependency, but it is only required for python < 3.8.

This is a trick to make the package noarch. When we drop py37 we can drop this workaround and keep it noarch. BTW, it is mostly harmless to install `importlib-metadata` in py>=38, the standard lib one is used.

**Comment by tacaswell** [comment]
OK, I'm going to close this and let nature take its course.

Sorry for the noise.

**Comment by hugovk** [comment]
Looks like CF can drop 3.7 now?

> ## 2022-08-24: Dropping Python 3.7
>
> Conda-Forge has been providing support for Python 3.7 for 4 years now. Increasingly projects are moving off it (particularly in the PyData community). With Python 3.11’s release coming around the corner (October 3rd), conda-forge plans to drop Python 3.7 support when Python 3.11 comes out. This will lighten the load on conda-forge infrastructure and make room for the new versions the community would like to support.
>
> More details can be found in issue [conda-forge-pinning-feedstock#2623](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2623). Feedback is welcome there.

https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7
